services:

  # vscode devcontainer (the service vscode will use as the interactive workspace container)
  vscode:

    # build from Dockerfile in context
    image: powershelldev-vscode
    build:
      context: build
      args:
        PowerShell_InstallModuleFast: "@{ ModuleName='Pode'; ModuleVersion='2.9.0' }, @{ ModuleName='Mdbc'; ModuleVersion='6.6.5' }, @{ ModuleName='Microsoft.Graph'; ModuleVersion='2.11.1' }"
      tags:
        - powershelldev-vscode

    # env_file(s) = ENV variables are set as the container launches up - so they are available at RUNTIME
    env_file:
      - ../.env

    # docker run -i / interactive
    # devcontainer should run interactive
    stdin_open: true

    # docker run -t / terminal
    # devcontainer should have a terminal
    tty: true

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # socket
      - /var/run/docker.sock:/var/run/docker.sock

      # .ssh
      - ~/.ssh:/root/.ssh

      # workspace
      - ..:/workspace:cached

      # profile.ps1
      - ../profile.ps1:/root/.config/powershell/profile.ps1:ro

  # oneshot container example
  oneshot:

    # build from Dockerfile in context
    image: powershelldev-oneshot
    build:
      context: build
      tags:
        - powershelldev-oneshot

    # env_file(s) = ENV variables are set as the container launches up - so they are available at RUNTIME
    env_file:
      - ../.env

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # workspace
      - ..:/workspace:cached

    command: pwsh -f /workspace/#oneshot.ps1

  # service container example
  service:

    # build from Dockerfile in context
    image: powershelldev-service
    build:
      context: build
      args:
        PowerShell_InstallModuleFast: "@{ ModuleName='Pode'; ModuleVersion='2.9.0' }"
      tags:
        - powershelldev-service

    # env_file(s) = ENV variables are set as the container launches up - so they are available at RUNTIME
    env_file:
      - ../.env

    # ports
    ports:
      - 80:80

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # workspace
      - ..:/workspace:cached

    command: pwsh -f /workspace/#service.ps1

  # mongo(db) - #justAnotherContainer
  mongo:

    # https://hub.docker.com/_/mongo/
    image: mongo:7-jammy

    # volumes
    volumes:

      # localtime
      - /etc/localtime:/etc/localtime:ro

      # data
      - ../data/mongo/configdb:/data/configdb:cached
      - ../data/mongo/db:/data/db:cached
